### PR TITLE
Css canvas medical - Luc-Ky Khuu

### PR DESCRIPTION
**Pull request by luc-ky-khuu**
css-canvas-medical

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Luc-ky! There is too much space between the regular anchor elements and the button anchor element in the `nav` as compared to the example, please revise and submit a new screenshot with your revision.

**Comment by luc-ky-khuu** [comment]
css-canvas-medical-nav-bar-revision

**Comment by luc-ky-khuu** [comment]
css-canvas-medical-020322-css-update

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Luc-ky! There should be no need for you to have each row in its own `container` class element, you should be able to have all `row` elements as children of one `container` class element.

**Comment by luc-ky-khuu** [comment]
css-canvas-medical-020422-update (2)

**Review by codingcodymiller — APPROVED** [review]
Nice work!

**Pull request merged**
